Support unclaiming bosh-lites
* Adds an optional 'operation' parameter that may be 'claim' (default) or 'unclaim'.
* If operation is 'unclaim', then the 'name' parameter must also be given to say which bosh-lite should be unclaimed.

[#160232135]

Signed-off-by: Luis Urraca <lurraca@pivotal.io>

diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -37,13 +37,26 @@ pushd sapi-env-pool > /dev/null
   git remote add push-target $uri
 popd > /dev/null
 
-pushd "$source" > /dev/null
-  export GIT_AUTHOR_NAME=$(cat $(jq -r '.params.author_name // ""' < $payload))
-  export GIT_AUTHOR_EMAIL=$(cat $(jq -r '.params.author_email // ""' < $payload))
-  export GIT_COMMITTER_NAME=$(cat $(jq -r '.params.committer_name // ""' < $payload))
-  export GIT_COMMITTER_EMAIL=$(cat $(jq -r '.params.committer_email // ""' < $payload))
+operation=$(jq -r '.params.operation // ""' < $payload)
+if [ -z "$operation" ]; then
+  operation="claim"
+fi
 
-  story=$(cat $(jq -r '.params.story // ""' < $payload))
+pushd "$source" > /dev/null
+  if [ "$operation" == "unclaim" ]; then
+    existing_bosh_lite_name=$(cat $(jq -r '.params.name // ""' < $payload))
+    export GIT_AUTHOR_NAME='Services API CI'
+    export GIT_AUTHOR_EMAIL='servicesapi@localhost'
+    export GIT_COMMITTER_NAME='Services API CI'
+    export GIT_COMMITTER_EMAIL='servicesapi@localhost'
+  else
+    export GIT_AUTHOR_NAME=$(cat $(jq -r '.params.author_name // ""' < $payload))
+    export GIT_AUTHOR_EMAIL=$(cat $(jq -r '.params.author_email // ""' < $payload))
+    export GIT_COMMITTER_NAME=$(cat $(jq -r '.params.committer_name // ""' < $payload))
+    export GIT_COMMITTER_EMAIL=$(cat $(jq -r '.params.committer_email // ""' < $payload))
+
+    story=$(cat $(jq -r '.params.story // ""' < $payload))
+  fi
 popd > /dev/null
 
 function msg {
@@ -169,6 +182,38 @@ EOF
   git add "${env_name}"
 }
 
+function unclaim_bosh_lite() {
+  working_pool="bosh-lites"
+  broken_pool="broken-bosh-lites"
+
+  if [ $# -eq 0 ]; then
+    echo "Usage: $0 env_name"
+    return 1
+  fi
+
+  env=$1
+
+  file="$(find "${working_pool}" -name "${env}")"
+
+  if [ "$file" == "" ]; then
+    echo "$env does not exist in ${working_pool}"
+    return 1
+  fi
+
+  git mv "${file}" "${broken_pool}/unclaimed/"
+  if [ -d "${env}" ]; then
+    git rm -rf "${env}" && \rm -rf "${env}"
+  fi
+
+  # trigger destroy-bosh-lite job
+  date +%s >| .trigger-bosh-lites-destroy && git add .trigger-bosh-lites-destroy
+
+  git commit --quiet -m"releasing $env" --no-verify
+  git push --quiet
+
+  echo "Done"
+}
+
 function commit_and_push() {
   git commit --quiet --message "CI-claim ${env} for ${story}"
   msg "Pushing reservation to $( basename $PWD )..."
@@ -176,13 +221,26 @@ function commit_and_push() {
 }
 
 >&2 cd sapi-env-pool
->&2 claim_random_environment $requested_input
-env_file="$(realpath $newfile)"
 
->&2 create_env_dir "${env_file}"
->&2 commit_and_push
+if [ "$operation" == "claim" ]; then
+  >&2 claim_random_environment $requested_input
+  env_file="$(realpath $newfile)"
 
-jq -n "{
-  version: {name: \"${env}\"},
-  metadata: []
-}" >&3
+  >&2 create_env_dir "${env_file}"
+  >&2 commit_and_push
+
+  jq -n "{
+    version: {name: \"${env}\"},
+    metadata: []
+  }" >&3
+elif [ "$operation" == "unclaim" ]; then
+  >&2 unclaim_bosh_lite "$existing_bosh_lite_name"
+
+  jq -n "{
+    version: {name: \"${existing_bosh_lite_name}\"},
+    metadata: []
+  }" >&3
+else
+  echo "invalid payload (expected operation to be 'claim' or 'unclaim')"
+  exit 1
+fi
